### ISSUE TITLE
DataFrame-related error 

### ISSUE THREAD

**Issue by gaelforget** [simonscmap/pycmap#2]
When I try to use get_dataset on either a Mac or a fresh binder instance I get this error message:

<img width="884" alt="Screen Shot 2020-03-30 at 2 16 36 PM" src="https://user-images.githubusercontent.com/20276764/77947167-7e1ee600-7291-11ea-98cf-8aac8befdce6.png">

Not sure what the fix is (I don't speak python) but maybe Pycmap needs updating to work with up to date dataFrame package? or maybe the Pycmap docs need to be revised wrt installation guidelines?

ps. this error does not occur when I use the binder link from this repo -- maybe because it has not recently been rebuilt or because a custom installation of packages is used...

**Comment by gaelforget** [comment]
>ps. this error does not occur when I use the binder link from this repo -- maybe because it has not recently been rebuilt or because a custom installation of packages is used...

In fact when I use your binder instance I get this warning instead: 

```
/usr/local/lib/python3.6/dist-packages/pycmap/rest.py:294: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  rows = int(df.ix[['count'], 'lat'])
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:961: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  return getattr(section, self.name)[new_key]
```

**Comment by mdashkezari** [comment]
right, this is a future version warning.
replacing .ix method with .loc addresses the warning.

upgrade to the latest pycmap version: 0.1.3
